package com.example.data

import android.util.Log
import com.example.api.JioSaavnApiClient
import com.example.api.SpotifyApiClient
import com.example.api.SpotifyTrackObject
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Zero-Client-ID Spotify Repository.
 * Uses extracted sp_dc session cookie to mint an active bearer token via Spotify's internal web player
 * and imports Liked Songs, User Playlists, and Taste Profile Affinities directly into Room.
 */
class SpotifyWebRepository(
    private val musicDao: MusicDao
) {
    private val TAG = "SpotifyWebRepository"

    data class ImportResult(
        val isSuccess: Boolean,
        val likedSongsCount: Int = 0,
        val playlistsCount: Int = 0,
        val topArtistsCount: Int = 0,
        val errorMessage: String? = null
    )

    suspend fun importSpotifyData(spDcCookie: String): ImportResult = withContext(Dispatchers.IO) {
        try {
            Log.d(TAG, "Minting Spotify Web Bearer Token using sp_dc cookie...")
            val cookieHeader = "sp_dc=$spDcCookie"
            val tokenResp = SpotifyApiClient.authApi.getAccessToken(cookieHeader)

            if (!tokenResp.isSuccessful || tokenResp.body()?.accessToken.isNullOrBlank()) {
                val err = "Failed to mint token from Spotify web endpoint: HTTP ${tokenResp.code()}"
                Log.e(TAG, err)
                return@withContext ImportResult(isSuccess = false, errorMessage = err)
            }

            val accessToken = tokenResp.body()!!.accessToken!!
            val authHeader = "Bearer $accessToken"
            Log.i(TAG, "Successfully minted active Spotify bearer token")

            var totalLiked = 0
            var totalPlaylists = 0
            var totalArtists = 0

            // 1. Ingest Liked Songs
            try {
                val likedResp = SpotifyApiClient.api.getLikedTracks(authHeader, limit = 50)
                val items = likedResp.body()?.items ?: emptyList()
                if (items.isNotEmpty()) {
                    val likedPlaylistId = musicDao.insertPlaylist(
                        PlaylistEntity(
                            name = "💚 Spotify Liked Songs",
                            description = "Imported from your personal Spotify library",
                            isAutoGenerated = false,
                            playlistType = "SPOTIFY_LIKED"
                        )
                    )

                    val songEntities = items.mapNotNull { it.track }.map { track ->
                        mapSpotifyTrackToSongEntity(track)
                    }

                    musicDao.insertSongs(songEntities)
                    songEntities.forEachIndexed { index, song ->
                        musicDao.addSongToPlaylist(
                            PlaylistSongCrossRef(
                                playlistId = likedPlaylistId,
                                songId = song.id,
                                sortOrder = index
                            )
                        )
                    }
                    totalLiked = songEntities.size
                    Log.i(TAG, "Imported $totalLiked liked songs into Room")
                }
            } catch (e: Exception) {
                Log.w(TAG, "Error importing liked tracks: ${e.message}")
            }

            // 2. Ingest User Playlists
            try {
                val playlistsResp = SpotifyApiClient.api.getUserPlaylists(authHeader, limit = 20)
                val playlists = playlistsResp.body()?.items ?: emptyList()
                for (pl in playlists) {
                    val pId = musicDao.insertPlaylist(
                        PlaylistEntity(
                            name = "Spotify: ${pl.name}",
                            description = pl.description ?: "Imported Spotify Playlist",
                            isAutoGenerated = false,
                            playlistType = "SPOTIFY_PLAYLIST"
                        )
                    )

                    try {
                        val tracksResp = SpotifyApiClient.api.getPlaylistTracks(authHeader, pl.id, limit = 50)
                        val tracks = tracksResp.body()?.items?.mapNotNull { it.track } ?: emptyList()
                        val entities = tracks.map { mapSpotifyTrackToSongEntity(it) }
                        musicDao.insertSongs(entities)
                        entities.forEachIndexed { idx, song ->
                            musicDao.addSongToPlaylist(
                                PlaylistSongCrossRef(
                                    playlistId = pId,
                                    songId = song.id,
                                    sortOrder = idx
                                )
                            )
                        }
                    } catch (e: Exception) {
                        Log.w(TAG, "Error fetching tracks for playlist ${pl.name}: ${e.message}")
                    }
                    totalPlaylists++
                }
            } catch (e: Exception) {
                Log.w(TAG, "Error importing user playlists: ${e.message}")
            }

            // 3. Ingest Taste Profile Affinity (Top Artists & Tracks)
            try {
                val topArtistsResp = SpotifyApiClient.api.getTopArtists(authHeader, limit = 50)
                val artists = topArtistsResp.body()?.items ?: emptyList()
                if (artists.isNotEmpty()) {
                    val affinities = artists.mapIndexed { index, artist ->
                        val normalizedWeight = (1.0f - (index * 0.018f)).coerceAtLeast(0.1f)
                        SpotifyAffinityEntity(
                            artist = artist.name,
                            weight = normalizedWeight,
                            rank = index + 1,
                            genres = artist.genres?.joinToString(", ") ?: "",
                            imageUrl = artist.images?.firstOrNull()?.url
                        )
                    }
                    musicDao.insertSpotifyAffinities(affinities)
                    totalArtists = affinities.size
                    Log.i(TAG, "Imported $totalArtists Spotify top artists into affinity table")
                }
            } catch (e: Exception) {
                Log.w(TAG, "Error importing top artists: ${e.message}")
            }

            ImportResult(
                isSuccess = true,
                likedSongsCount = totalLiked,
                playlistsCount = totalPlaylists,
                topArtistsCount = totalArtists
            )
        } catch (e: Exception) {
            Log.e(TAG, "Fatal error during Spotify import: ${e.message}", e)
            ImportResult(isSuccess = false, errorMessage = e.message ?: "Unknown network error")
        }
    }

    /**
     * Maps Spotify track to Pulse Music SongEntity.
     * Generates a stable unique ID based on Spotify Track ID.
     */
    private fun mapSpotifyTrackToSongEntity(track: SpotifyTrackObject): SongEntity {
        val artistName = track.artists?.joinToString(", ") { it.name } ?: "Unknown Artist"
        val albumName = track.album?.name ?: "Single"
        val artUrl = track.album?.images?.firstOrNull()?.url

        val numericId = (track.id.hashCode().toLong() and 0x7FFFFFFF) + 8_000_000L

        return SongEntity(
            id = numericId,
            title = track.name,
            artist = artistName,
            album = albumName,
            durationMs = track.durationMs ?: 180000L,
            contentUri = "spotify://track/${track.id}", // Will be dynamically bridged to JioSaavn stream on play
            streamUrl = null,
            albumArtUri = artUrl,
            coverArtUrl = artUrl,
            sourceType = "ONLINE",
            isDownloaded = false,
            downloadProgress = 0,
            languageScript = inferLanguage(track.name, artistName),
            genre = "Spotify Import"
        )
    }

    private fun inferLanguage(title: String, artist: String): String {
        val combined = "$title $artist".lowercase()
        return when {
            combined.any { it.code in 0x0A00..0x0A7F } || combined.contains("punjabi") || combined.contains("sidhu") || combined.contains("diljit") || combined.contains("aujla") -> "PUNJABI"
            combined.any { it.code in 0x0900..0x097F } || combined.contains("marathi") || combined.contains("ajay atul") -> "MARATHI"
            else -> "HINDI"
        }
    }
}
